config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root 'home#index'

  resources :units
  resources :clients
  resources :taxpayers
  resources :categories
  resources :lawyers
  resources :contracts
  resources :proposals
  resources :proposal_tickets
  resources :cnas
  resources :cities
  resources :taxpayer_contacts
  resources :histories
  resources :remittances
  resources :bank_billets
  resources :discharges
  resources :users
  resources :words
  resources :tickets

  resources :user, :controller => 'users'

  resources :home do
    collection do
      get 'filter_name' => 'home#filter_name'
      get :get_tasks
      get :get_click
    end
  end

  get 'get_client' => 'clients#get_client'
  get 'set_client' => 'clients#set_client'

  get 'home/:cod/show' => 'home#show', as: :show
  get 'home/:cod/deal' => 'home#deal', as: :deal
  get 'home/:cod/get_cna' => 'home#get_cna', as: :get_cna
  patch 'home/:cod/pay_cna' => 'home#pay_cna', as: :pay_cna
  patch 'home/:cod/set_cna_to_normal' => 'home#set_cna_to_normal', as: :set_cna_to_normal
  patch 'home/:cod/set_cna' => 'home#set_cna', as: :set_cna
  get 'home/:cod/set_charge_cna' => 'home#set_charge_cna', as: :set_charge_cna
  get 'home/:cod/get_tickets' => 'home#get_tickets', as: :get_tickets
  get 'home/:cod/set_tickets' => 'home#set_tickets', as: :set_tickets
  get 'home/:cod/get_taxpayer' => 'home#get_taxpayer', as: :get_taxpayer
  patch 'home/:cod/set_taxpayer' => 'home#set_taxpayer', as: :set_taxpayer
  get 'home/:cod/set_lawyer_to_cna' => 'home#set_lawyer_to_cna', as: :set_lawyer_to_cna

  post 'proposal/:cod/create_proposal' => 'proposals#create_proposal', as: :create_proposal
  post 'proposal/:cod/cancel_proposal' => 'proposals#cancel_proposal', as: :cancel_proposal

  post 'contract/:cod/create_contract_from_proposal' => 'contracts#create_contract_from_proposal', as: :create_contract_from_proposal
  post 'contract/:cod/create_contract' => 'contracts#create_contract', as: :create_contract
  get 'contract/:contract/delete_contract' => 'contracts#delete_contract', as: :delete_contract
  get 'contract/:cod/contract_pdf' => 'contracts#contract_pdf', as: :contract_pdf
  get 'contract/:cod/contract_transaction_pdf' => 'contracts#contract_transaction_pdf', as: :contract_transaction_pdf
  get 'contract/:cod/create_bank_billet' => 'contracts#create_bank_billet', as: :create_bank_billet

  get 'ticket/:cod/create_new_expire_at' => 'tickets#create_new_expire_at', as: :create_new_expire_at
  get 'ticket/:cod/update_status_ticket' => 'tickets#update_status_ticket', as: :update_status_ticket
  
  post 'remittance/remittance_create' => 'remittances#remittance_create', as: :remittance_create
  get 'remittance/remittance_new' => 'remittances#remittance_new', as: :remittance_new
  get 'remittance/:cod/remittance_download' => 'remittances#remittance_download', as: :remittance_download
  get 'bank_billet/:cod/bank_billet_show' => 'bank_billets#bank_billet_show', as: :bank_billet_show
  get 'bank_billet/:cod/bank_billet_cancel' => 'bank_billets#bank_billet_cancel', as: :bank_billet_cancel
  get 'discharge/sent_discharge' => 'discharges#sent_discharge', as: :sent_discharge
  post 'discharge/create_discharge' => 'discharges#create_discharge', as: :create_discharge

  get 'contract/report_payment_filter' => 'contracts#report_payment_filter', as: :report_payment_filter
  get 'contract/report_payment_action' => 'contracts#report_payment_action', as: :report_payment_action
  get 'contract/report_payment_action_pdf' => 'contracts#report_payment_action_pdf', as: :report_payment_action_pdf

  get 'contract/report_fee_filter' => 'contracts#report_fee_filter', as: :report_fee_filter
  get 'contract/report_fee_action' => 'contracts#report_fee_action', as: :report_fee_action
  
  get 'history/report_count_contacts_filter' => 'histories#report_count_contacts_filter', as: :report_count_contacts_filter
  get 'history/report_count_contacts_action' => 'histories#report_count_contacts_action', as: :report_count_contacts_action

  get 'cna/report_cna_lawyer_filter' => 'cnas#report_cna_lawyer_filter', as: :report_cna_lawyer_filter
  get 'cna/report_cna_lawyer_rel' => 'cnas#report_cna_lawyer_rel', as: :report_cna_lawyer_rel

end

app/models/cna.rb
class Cna < ActiveRecord::Base
  belongs_to :unit
  belongs_to :taxpayer
  belongs_to :contract
  belongs_to :client
  
  enum status: [:not_pay, :pay, :contract, :proposal]
  enum stage: [:lawyer, :normal]

#  usar_como_dinheiro :amount

  def self.list(unit, client)
    self.where("unit_id = ? AND client_id = ?", unit, client)
  end

  def self.list_open(taxpayer)
    self.where('taxpayer_id = ? AND status in (0,2,3)', taxpayer)
  end
  
end

app/controllers/cnas_controller.rb
class CnasController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  respond_to :html
  layout 'window'

  def index
    @cnas = Cna.where("unit_id = ?", current_user.unit_id).paginate(:page => params[:page], :per_page => 20)
    respond_with @cnas, :layout => 'application'
  end

  def show
    @cna = Cna.find(params[:id])
    respond_with @cna
  end

  def new
    @cna = Cna.new
    @cna.unit_id = current_user.unit_id
    @cna.client_id = session[:client_id]
    @cna.taxpayer_id = params[:format]
  end

  def edit
    @cna = Cna.find(params[:id])
  end

  def create
    @cna = Cna.new(cna_params)
    @cna.unit_id = current_user.unit_id
    @cna.client_id = session[:client_id]
    @cna.stage = 1
    @cna.status = 0
    @cna.fl_charge = 0
    @cna.start_at = Date.current
    @cna.due_at = Date.new(@cna.year, 5, 22)
    @cna.save!

    @taxpayer = Taxpayer.find(@cna.taxpayer_id)
    respond_with @taxpayer
  end

  def update
    @cna = Cna.find(params[:id])
    @cna.update_attributes(cna_params)
    redirect_to( taxpayer_path(@cna.taxpayer.id))
  end

  def report_cna_lawyer_filter
  end

  def report_cna_lawyer_rel
    if params[:report][:user_id].empty?
      @rels = Cna.lawyer.where('unit_id = ? and client_id = ?', current_user.unit_id, session[:client_id])
    else
      @rels = Cna.joins(:taxpayer).lawyer.where('cnas.unit_id = ? and cnas.client_id = ? and taxpayers.user_id = ?', current_user.unit_id, session[:client_id], params[:report][:user_id])
    end 
  end


  private
    def cna_params
      params.require(:cna).permit(:fl_charge, :amount, :status, :stage, :nr_document, :taxpayer_id, :unit_id, :year, :client_id)
    end
end

app/views/cnas/_form.html.erb
<div class='section'>
  <div class='label1 top req'> <%=t("taxpayer.id") %>: </div>  <%= @cna.taxpayer.id %>
  <div class='label1 top req'> <%=t("taxpayer.origin_code") %>: </div>  <%= @cna.taxpayer.origin_code %>
  <div class='label1 top req'> <%=t("taxpayer.name") %>: </div>  <%= @cna.taxpayer.name %>
  <div class='label1 top req'> <%=t("cna.id") %>: </div>  <%= @cna.id %>
</div>
<br>

<%= simple_form_for(@cna) do |f| %>
	<div class='section'>
    <%= f.input :unit_id, as: :hidden %>
    <%= f.input :taxpayer_id, as: :hidden %>
    <%= f.input :year, :label => t('cna.year'), input_html:{:class => 'form-control'} %>
    <%= f.input :nr_document, :label => t('cna.nr_document'), input_html:{:class => 'form-control'} %>
    <%= f.input :amount, :label => t('cna.amount'), input_html:{:class => 'form-control'} %>

		<div class="actions">
			<div class='buttonbar'>
				<%= f.button :submit, t('menu.save'), class: 'btn-primary' %>
				<%= 'ou' %>
				<%= link_to t('menu.cancel'), :back %>
			</div>
		</div>
	</div>
<% end %>

app/views/cnas/edit.html.erb
<div class='title'> <%= t('cna.edit') %> </div>

<%= render "form"%>

app/views/cnas/index.html.erb
<div class='title_tools'>
	<a class="btn btn-large btn-warning" <%= link_to(t('cna.new'), new_cna_path) %> </a>
</div>

<div class='title_page'>
	<span> <%= t('cna.title') %> </span>
</div>

<div class='list1'>
	<% unless @cnas.empty? %>
		<% @cnas.each do |cna| %>
			<li>
				<div class='strip' id='none'> <%= cna.id %> </div>

				<div class='tools'>
					<%= link_to(t('menu.edit'), edit_cna_path(cna), class: "btn btn-xs btn-default") %>
				</div>

				<div class='indent'>
					<%= link_to(cna.taxpayer.name, cna_path(cna)) %>
					&ndash;
					<tt>
					<%= cna.year %>
					</tt>
					<dt>
					</dt>
				</div>
			</li>
		<% end %>
	<% end %>
</div>

<div id='paginate'><%= render 'common/paginate' %></div>

app/views/cnas/new.html.erb
<div class='title'> <%= t('cna.new') %> </div>

<%= render "form"%>

app/views/cnas/report_cna_lawyer_filter.html.erb
<%= simple_form_for(
    :report, 
    url: 'report_cna_lawyer_rel', 
    method: :get,
    html: { class: 'form-horizontal' }, 
            wrapper: :horizontal_form,
            wrapper_mappings: {
            check_boxes: :horizontal_radio_and_checkboxes,
            radio_buttons: :horizontal_radio_and_checkboxes,
            file: :horizontal_file_input,
            boolean: :horizontal_boolean
  }) do |f| %>

  <div class='title'> Relatório de CNAs AJUIZADAS </div>
  
  <div class='section'>

    <%= f.input :ini_at, readonly: true, label: 'Data Inicial', skip_label: true %>
    <%= f.input :end_at, readonly: true, label: 'Data Final', skip_label: true %>
    <%= f.input :user_id, collection: User.list(current_user.unit_id), label: 'Colaborador(a)' %>

    <div class='buttonbar'>
      <%= f.button :submit, 'Gerar Relatório', class: 'btn-primary' %>
      <%= 'ou' %>
      <%= link_to t('menu.cancel'), root_path %>
    </div>
  </div>
<% end %>

app/views/cnas/report_cna_lawyer_rel.html.erb
<div class='title_tools'>
  <%= link_to('Voltar para Filtros', report_cna_lawyer_filter_path, class: "btn btn-large btn-default") %> </a>
</div>

<div class='title_page'>
  <span> <%= 'Relatório de CNAs AJUIZADAS' %> </span>
</div>

<div class='section'>
  <div class='label1 top req'> <%= 'Data Inicial' %>: </div>    <%= params[:report][:ini_at] %>
  <div class='label1 top req'> <%= 'Data Final' %>: </div>      <%= params[:report][:end_at] %>
  <div class='label1 top req'> <%= 'Colaborador(a)' %>: </div>  
  <%= User.find(params[:report][:user_id]).name if params[:report][:user_id].present? %>
</div>

<table class="table" border="0">
  <thead>
    <tr>
      <th>Contribuinte</th>
      <th>CPF</th>
      <th>Exercício</th>
      <th>Valor</th>
      <th>Colaborador(a)</th>
    </tr>
  </thead>
  <tbody>
    <% unless @rels.nil? %>
      <% @rels.each do |rel| %>
        <tr>
          <td><%= link_to(rel.taxpayer.name, show_path(rel.taxpayer_id)) %> </td>
          <td><%= rel.taxpayer.cpf %> </td>
          <td><%= rel.year %> </td>
          <td><%= rel.amount.real %> </td>
          <td><%= rel.taxpayer.user.name %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>TOTAL em JUIZO</td>
      <td></td>
      <td></td>
      <td><%= @rels.map{|i|i[:amount]}.inject(:+).real if @rels %></td>
      <td></td>
    </tr>
  </tfoot>  
</table>