config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root 'home#index'

  resources :units
  resources :clients
  resources :taxpayers
  resources :categories
  resources :lawyers
  resources :contracts
  resources :proposals
  resources :proposal_tickets
  resources :cnas
  resources :cities
  resources :taxpayer_contacts
  resources :histories
  resources :remittances
  resources :bank_billets
  resources :discharges
  resources :users
  resources :words
  resources :tickets

  resources :user, :controller => 'users'

  resources :home do
    collection do
      get 'filter_name' => 'home#filter_name'
      get :get_tasks
      get :get_click
    end
  end

  get 'get_client' => 'clients#get_client'
  get 'set_client' => 'clients#set_client'

  get 'home/:cod/show' => 'home#show', as: :show
  get 'home/:cod/deal' => 'home#deal', as: :deal
  get 'home/:cod/get_cna' => 'home#get_cna', as: :get_cna
  patch 'home/:cod/pay_cna' => 'home#pay_cna', as: :pay_cna
  patch 'home/:cod/set_cna_to_normal' => 'home#set_cna_to_normal', as: :set_cna_to_normal
  patch 'home/:cod/set_cna' => 'home#set_cna', as: :set_cna
  get 'home/:cod/set_charge_cna' => 'home#set_charge_cna', as: :set_charge_cna
  get 'home/:cod/get_tickets' => 'home#get_tickets', as: :get_tickets
  get 'home/:cod/set_tickets' => 'home#set_tickets', as: :set_tickets
  get 'home/:cod/get_taxpayer' => 'home#get_taxpayer', as: :get_taxpayer
  patch 'home/:cod/set_taxpayer' => 'home#set_taxpayer', as: :set_taxpayer
  get 'home/:cod/set_lawyer_to_cna' => 'home#set_lawyer_to_cna', as: :set_lawyer_to_cna

  post 'proposal/:cod/create_proposal' => 'proposals#create_proposal', as: :create_proposal
  post 'proposal/:cod/cancel_proposal' => 'proposals#cancel_proposal', as: :cancel_proposal

  post 'contract/:cod/create_contract_from_proposal' => 'contracts#create_contract_from_proposal', as: :create_contract_from_proposal
  post 'contract/:cod/create_contract' => 'contracts#create_contract', as: :create_contract
  get 'contract/:contract/delete_contract' => 'contracts#delete_contract', as: :delete_contract
  get 'contract/:cod/contract_pdf' => 'contracts#contract_pdf', as: :contract_pdf
  get 'contract/:cod/contract_transaction_pdf' => 'contracts#contract_transaction_pdf', as: :contract_transaction_pdf
  get 'contract/:cod/create_bank_billet' => 'contracts#create_bank_billet', as: :create_bank_billet

  get 'ticket/:cod/create_new_expire_at' => 'tickets#create_new_expire_at', as: :create_new_expire_at
  get 'ticket/:cod/update_status_ticket' => 'tickets#update_status_ticket', as: :update_status_ticket
  
  post 'remittance/remittance_create' => 'remittances#remittance_create', as: :remittance_create
  get 'remittance/remittance_new' => 'remittances#remittance_new', as: :remittance_new
  get 'remittance/:cod/remittance_download' => 'remittances#remittance_download', as: :remittance_download
  get 'bank_billet/:cod/bank_billet_show' => 'bank_billets#bank_billet_show', as: :bank_billet_show
  get 'bank_billet/:cod/bank_billet_cancel' => 'bank_billets#bank_billet_cancel', as: :bank_billet_cancel
  get 'discharge/sent_discharge' => 'discharges#sent_discharge', as: :sent_discharge
  post 'discharge/create_discharge' => 'discharges#create_discharge', as: :create_discharge

  get 'contract/report_payment_filter' => 'contracts#report_payment_filter', as: :report_payment_filter
  get 'contract/report_payment_action' => 'contracts#report_payment_action', as: :report_payment_action
  get 'contract/report_payment_action_pdf' => 'contracts#report_payment_action_pdf', as: :report_payment_action_pdf

  get 'contract/report_fee_filter' => 'contracts#report_fee_filter', as: :report_fee_filter
  get 'contract/report_fee_action' => 'contracts#report_fee_action', as: :report_fee_action
  
  get 'history/report_count_contacts_filter' => 'histories#report_count_contacts_filter', as: :report_count_contacts_filter
  get 'history/report_count_contacts_action' => 'histories#report_count_contacts_action', as: :report_count_contacts_action

  get 'cna/report_cna_lawyer_filter' => 'cnas#report_cna_lawyer_filter', as: :report_cna_lawyer_filter
  get 'cna/report_cna_lawyer_rel' => 'cnas#report_cna_lawyer_rel', as: :report_cna_lawyer_rel

end

app/models/home.rb
class Home < ActiveRecord::Base

  def self.calc_meses_atraso(_year)
  	date_base = Date.new(_year, 5, 22)
  	date_today = Date.today()
  	(date_today.year * 12 + date_today.month) - (date_base.year * 12 + date_base.month)
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :start => start_at.rfc822,
      :end => end_at.rfc822,
      :allDay => allDay,
      :user_name => self.user_name,
      :url => Rails.application.routes.url_helpers.events_path(id),
      :color => "green"
    }
  end
  
end

app/controllers/home_controller.rb
 class HomeController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :js, :json

  layout 'application'

  def index
  	session[:unit_id] = current_user.unit.id
  	session[:unit_name] = current_user.unit.name
    session[:unit_bank_billet_account] = 21
    session[:taxpayer_id] = nil

    if current_user.profile == 'client'
      session[:client_id] = 1
      session[:client_name] = 'FAESC'
    end

    if session[:client_id].nil?
      redirect_to(controller: :clients, action: :get_client)  and return
    end
    
    contracts_meter
  end


  def filter_name
    
    if params[:filter][:name].present?

      if params[:filter][:name].size < 3
        flash[:alert] = "Nome do contribuinte deve conter ao menos 3 letras."
        redirect_to :root and return
      end 

      @taxpayers = Taxpayer
                    .joins(:city)
                    .where("taxpayers.unit_id = ? AND taxpayers.client_id = ? AND lower(taxpayers.name) like ?", current_user.unit_id, session[:client_id], "%"<< params[:filter][:name].downcase << "%")
                    .paginate(:page => params[:page], :per_page => 5)
                    .order('name ASC')

    elsif params[:filter][:cpf].present?

      unless params[:filter][:cpf].size == 14
        flash[:alert] = "CPF deve conter 11 números no formato 999.999.999-99"
        redirect_to :root and return
      end 

      @taxpayers = Taxpayer
                    .joins(:city)
                    .where("taxpayers.unit_id = ? AND taxpayers.client_id = ? AND taxpayers.cpf = ?", current_user.unit_id, session[:client_id], params[:filter][:cpf])
                    .paginate(:page => params[:page], :per_page => 5)
                    .order('name ASC')

    elsif params[:filter][:cna].present?

      @taxpayers = Taxpayer
                    .where("unit_id = ? AND origin_code = ?", current_user.unit_id, params[:filter][:cna])
                    .paginate(:page => params[:page], :per_page => 5)
                    .order('name ASC')

    else

      flash[:alert] = "Nenhum filtro preenchido."
      redirect_to :root and return
    end 

    if @taxpayers.count == 0
      flash[:alert] = "Não encontrado contribuinte."
      redirect_to :root and return
    end 

    contracts_meter

    render "index", :layout => 'application'
  end


  def show
    @taxpayer = Taxpayer.find(params[:cod])

    unless current_user.admin?
     if @taxpayer.user_id != current_user.id
       flash[:alert] = "Contribuinte não pertence a sua lista."
       redirect_to :root and return
     end 
    end

    @contacts = TaxpayerContact.where('taxpayer_id = ?', params[:cod])

    @cnas_negotiables = Cna.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ? AND status = 0 AND stage = 1', params[:cod]).order(:year, :due_at)
    @cnas_lawyers = Cna.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ? AND stage = 0', params[:cod]).order(:year, :due_at)
    @cnas_not_negotiables = Cna.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ? AND status in (1,2,3) AND stage = 1', params[:cod]).order(:year)

    @contracts_for_taxpayer = Contract.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ?', params[:cod])
    
    clear_variable_session()
    contracts_meter

    @histories = History.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ?', params[:cod]).order('created_at DESC')

    session[:taxpayer_id] = params[:cod]

    render "index", :layout => 'application'
  end



  def deal

    if params[:date_current].nil?
      @date_current = Date.current
    else
      @date_current = Date.new(params[:date_current][:year].to_i, params[:date_current][:month].to_i, params[:date_current][:day].to_i)
    end

    if params[:data_base].present? && params[:data_base][:date_current].present?
      @date_current = params[:data_base][:date_current].to_date
    else
      @date_current = Date.current
    end

    if @date_current < Date.current
      flash[:alert] = "Data base não pode ser menor que data atual"
      @date_current = nil
      redirect_to deal_path(params[:cod]) and return 
    end

    if current_user.client?
      flash[:alert] = "Não permitido acessar Ambiente de Negociações!"
      redirect_to show_path(params[:cod]) and return 
    end

    @taxpayer = Taxpayer.find(params[:cod])

    unless current_user.admin?
      if @taxpayer.user_id != current_user.id
        flash[:alert] = "Contribuinte não pertence a sua lista."
        redirect_to :root and return
      end
    end
 
    unless Taxpayer.chargeble? @taxpayer
      flash[:alert] = "Cidade não liberada para negociações!"
      redirect_to show_path(params[:cod]) and return 
    end

    @contacts = TaxpayerContact.where('taxpayer_id = ?', params[:cod])

    @areas = Area.list(current_user.unit_id).where('taxpayer_id = ?', params[:cod]).order('year DESC, nr_document')
    @histories = History.list(current_user.unit_id, session[:client_id]).where('taxpayer_id = ?', params[:cod]).order('created_at DESC')

    @contract = Contract.new
    @contract.unit_ticket_quantity = 1
    @contract.client_ticket_quantity = 1

    @cnas = Cna.list(current_user.unit_id, session[:client_id]).not_pay.normal.where('taxpayer_id = ?', params[:cod]).order(:year, :due_at)
    @cna = Cna.new

    clear_variable_session()

    respond_with @taxpayer, :layout => 'application'     
  end


  def get_cna
    @cna = Cna.find(params[:cod])
  end

  
  def set_cna
    @cna = Cna.find(params[:cod])
    @cna.update_attributes(cna_params)

    @cnas = Cna.list(current_user.unit_id, session[:client_id]).not_pay.where('taxpayer_id = ?', @cna.taxpayer.id).order(:year)
    @taxpayer = Taxpayer.find @cna.taxpayer.id

    if params[:date_current].nil?
      @date_current = Date.current
    else
      @date_current = Date.new(params[:date_current][:year].to_i, params[:date_current][:month].to_i, params[:date_current][:day].to_i)
    end
    
    clear_variable_session()

  end


  def set_charge_cna
    @cna = Cna.find(params[:cod])
    @cna.fl_charge = @cna.fl_charge == true ? false : true
    @cna.save!

    @cnas = Cna.list(current_user.unit_id, session[:client_id]).not_pay.normal.where('taxpayer_id = ?', @cna.taxpayer.id).order(:year)
    @taxpayer = Taxpayer.find @cna.taxpayer.id

    if params[:date_current].nil?
      @date_current = Date.current
    else
      @date_current = Date.new(params[:date_current][:year].to_i, params[:date_current][:month].to_i, params[:date_current][:day].to_i)
    end
    clear_variable_session()
  end


  def set_lawyer_to_cna

    begin
      ActiveRecord::Base.transaction do

        @cna = Cna.find(params[:cod])
        @cna.stage = @cna.normal? ? :lawyer : :normal
        @cna.fl_charge = false
        @cna.save!

        history = History.new
        history.unit_id = current_user.unit_id
        history.client_id = @cna.client_id
        history.taxpayer_id = @cna.taxpayer_id
        history.user_id = current_user.id
        history.word_id = 4 ## Ajuizado
        history.history_date = Time.current
        history.description = 'CNA referente ' + @cna.year.to_s + ' marcada para AJUIZAR.'
        history.save!      

      end
      rescue ActiveRecord::RecordInvalid => e
      puts e.record.errors.full_messages
    end  

    @cnas = Cna.list(current_user.unit_id, session[:client_id]).not_pay.normal.where('taxpayer_id = ?', @cna.taxpayer.id).order(:year)
    @taxpayer = Taxpayer.find @cna.taxpayer.id

    if params[:date_current].nil?
      @date_current = Date.current
    else
      @date_current = Date.new(params[:date_current][:year].to_i, params[:date_current][:month].to_i, params[:date_current][:day].to_i)
    end
    clear_variable_session()
  end


  def pay_cna
    if current_user.id == 1
      @cna = Cna.find(params[:cod])
      @cna.pay!

      redirect_to show_path(@cna.taxpayer_id) and return
    end
  end


  def set_cna_to_normal
    if current_user.id == 1
      @cna = Cna.find(params[:cod])
      @cna.normal!

      redirect_to show_path(@cna.taxpayer_id) and return
    end
  end


  def get_tickets
    unit_ticket_quantity  =  params[:ticket][:unit_ticket_quantity].to_i
    unit_ticket_due       =  params[:ticket][:unit_ticket_due].to_date
    client_ticket_due     =  params[:ticket][:client_ticket_due].to_date

    if params[:ticket][:value_type].to_i == 0
      total_cna_a_vista = session[:total_cna_a_vista].to_f
      total_fee = session[:total_fee_a_vista].to_f.round(2)
      total_cna = total_cna_a_vista - total_fee      
    else
      total_cna_cobrado = session[:total_cna_cobrado].to_f
      total_fee = (session[:total_fee_cobrado].to_f).round(2)
      total_cna = total_cna_cobrado - total_fee      
    end

    cna_ticket = total_cna / unit_ticket_quantity.to_i
    @tickets = []

    unit_ticket_quantity  = unit_ticket_quantity + 1

    (1..unit_ticket_quantity).each  do |tic|
      unit_due = unit_ticket_due if tic == 1
      client_due = client_ticket_due if tic == 2
      client_due = client_ticket_due + (tic - 2).month if tic > 2

      ticket = { ticket: tic, unit_amount: total_fee, client_amount: 0.00, due: unit_due} if tic == 1
      ticket = { ticket: tic, unit_amount: 0.00, client_amount: cna_ticket.round(2), due: client_due} if tic > 1
      @tickets << ticket
      session[:tickets] = @tickets
    end
  end

  
  def get_taxpayer
    @taxpayer = Taxpayer.find(params[:cod])
  end

  def set_taxpayer
    @taxpayer = Taxpayer.find(params[:cod])
    @taxpayer.update_attributes(taxpayer_params)
  end



  private
  def cna_params
    params.require(:cna).permit(:fl_charge)
  end

  def taxpayer_params
    params.require(:taxpayer).permit(:phone)
  end

  def clear_variable_session
    session[:value_cna] = 0
    session[:total_multa] = 0
    session[:total_juros] = 0
    session[:total_correcao] = 0
    session[:total_cna] = 0

    session[:value_cna_cobrado] = 0

app/views/home/_cnas.html.erb
<%= simple_form_for(
    :data_base,
    url: deal_path(@taxpayer),
    method: :get,
    html: { class: 'form-horizontal' }, 
    wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>

  <%= f.error_notification %>

  <div class='section'>
    <%= f.input :date_current, as: :string, label: 'Data base para efetuar os cálculos: ' << @date_current.to_s_br, hint: 'Clique aqui para informar outra data base ou digite a data no formato "' << Date.current.to_s_br << '"' %>

    <div class='buttonbar'>
      <%= f.button :submit, 'Atualizar data base de cálculo', class: 'btn-primary' %>
    </div>
  </div>
<% end %>

<div class='subtitle'> <%= t('deal.cnas', data_base: @date_current.to_s_br) %>  </div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Ano</th>
      <th><%= t('status') %></th>
      <th>Meses</th>
      <th>Valor Principal</th>
      <th>Correção</th>
      <th>Multa</th>
      <th>Juros</th>
      <th>Valor Total</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% unless @cnas.nil? %>
      <% @cnas.each do |cna| %>
        <tr>
          <td>
            <% if cna.fl_charge %>
              <div class='strip green'> <%= 'COBRAR' %> </div>
            <% else %>
              <div class='strip red' id='none'> <%= 'NÃO COBRAR' %> </div>
            <% end %> 
          </td>    
          <td>
            <% if cna.fl_charge %>
              <span class="label label-success"><%= cna.year %></span>
            <% else %>
              <%= cna.year %> 
            <% end %> 
          </td>
          <td><%= t(cna.status) %> </td>
          <td><%= calc_meses_atraso(cna, nil, @date_current) %> </td>
          <td><%= cna.amount.real %> </td>
          <td><%= calc_correcao(cna, nil, @date_current).real %> </td>
          <td><%= calc_multa(cna, nil, @date_current).real %> </td>
          <td><%= calc_juros(cna, nil, @date_current).real %> </td>
          <td> 
            <% if cna.fl_charge %>
              <span class="label label-success"><%= calc_cna(cna, nil, @date_current).real %></span>
            <% else %>
              <%= calc_cna(cna, nil, @date_current).real %>
            <% end %>
          </td>
          <td><%= link_to(cna.fl_charge ? 'Marcar para NÃO cobrar valor' : 'Marcar para cobrar valor', set_charge_cna_path(cna), class: "btn btn-xs btn-default", remote: true ) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td> <%= session[:value_cna].real %></td>
      <td> <%= session[:total_correcao].real %></td>
      <td> <%= session[:total_multa].real %> </td>
      <td> <%= session[:total_juros].real %> </td>
      <td> <%= session[:total_cna].real %></td>
      <td></td>
    </tr>
  </tfoot>  
</table>

<%= render 'totais' %>

app/views/home/_index_contracts.html.erb
<div class='title_page'> <%= t('home.contract.title') %> </div>
<table class="table">
  <thead>
    <tr>
      <th>Termo</th>
      <th>Situação</th>
      <th>Data Contrato</th>
      <th>Parcela(s) GMA</th>
      <th>Valor GMA</th>
      <th><%= 'Parcela(s) ' << session[:client_name] %></th>
      <th><%= 'Valor ' << session[:client_name] %> </th>
    </tr>
  </thead>
  <tbody>
    <% if @contracts.nil? %>
      'Nenhum TERMO gerado para o contribuinte.'
    <% else %>
      <% @contracts.each do |contract| %>
        <tr>
          <td><%= contract.id %> </td>
          <td><%= link_to(t('contract.status.' << contract.status) << ' - Ver Termo', contract_path(contract)) %> </td>
          <td><%= contract.contract_date.to_s_br %> </td>
          <td><%= contract.unit_ticket_quantity %> </td>
          <td><%= contract.unit_amount.real %> </td>
          <td><%= contract.client_ticket_quantity %> </td>
          <td><%= contract.client_amount.real %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/home/_index_last_contracts.html.erb
<div class='subtitle'> <%= 'Últimos 5 Contratos Fechados' %> </div>

<div class='list1'>
  <% unless @contracts.empty? %>
    <% @contracts.each do |contract| %>
      <li>
        <div class='strip' id='none'> <%= contract.id %> </div>

        <div class='indent'>
          <% if contract.cancel? %>
            <span class="label label-danger"><%= 'CANCELADO' %> </span> 
          <% elsif contract.active? %>
            <span class="label label-primary"><%= 'ATIVO' %> </span> 
          <% elsif contract.paid? %>
            <span class="label label-success"><%= 'PAGO' %> </span> 
          <% else %>
            <span><%= 'NAO DEFINIDO' %> </span> 
          <% end %>
          &nbsp;
          &bull;
          <%= contract.taxpayer.origin_code %>
          &bull;
          <%= link_to(contract.taxpayer.name, contract_path(contract)) %>
          &bull;
          <tt>
            <%= 'Data do Contrato: ' << contract.contract_date.to_s_br %>
            &bull;
            <%= 'Colaborador(a): ' << contract.user.name %>
          </tt>
          <dt></dt>
        </div>
      </li>
    <% end %>
  <% else %>
    Colaborador não tem termos gerados.
  <% end %>
</div>

app/views/home/_tickets.html.erb
<div class='title_tools'>
  <a class="btn btn-large btn-default" <%= link_to(t('deal.recalculate'), :back) %> </a>
  <a class="btn btn-large btn-success" <%= link_to(t('deal.create_proposal'), create_proposal_path, method: :post ) %> </a>
  <a class="btn btn-large btn-success" <%= link_to(t('deal.create_contract'), create_contract_path, method: :post ) %> </a>
</div>

<br>
<div class='subtitle'> <%= t('deal.ticket') %> </div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Valor de Parcela GMA</th>
      <th>Valor de Parcela Cliente</th>
      <th>Vencimento</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td>Totais</td>
      <td><%= @tickets.map{|i|i[:unit_amount]}.inject(:+).real if @tickets %></td>
      <td><%= @tickets.map{|i|i[:client_amount]}.inject(:+).real if @tickets %></td>
      <td></td>
    </tr>
  </tfoot>  
  <tbody>
    <% unless @tickets.nil? %>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket[:ticket] %> </td>
          <td><%= ticket[:unit_amount].real %> </td>
          <td><%= ticket[:client_amount].real %> </td>
          <td><%= ticket[:due].to_s_br %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class='title_tools'>
  <a class="btn btn-large btn-default" <%= link_to('Procurar Novo Contribuinte', root_path ) %> </a>
  <button class="btn btn-success" type="button">
    Termos Fechados Hoje: &nbsp; <span class="badge"> <%= @count_contracts_deal_day %> </span>
  </button>
  <button class="btn btn-primary" type="button">
    Termos Fechados no MES: &nbsp; <span class="badge"> <%= @count_contracts_deal_month %> </span>
  </button>
</div>

<div class='title_page'>
  <span> <%= current_user.client? ? t('home.title_client') : 'Tela Inicial de ' << current_user.name %> </span>
</div>


<% if @taxpayer.nil? %>

  <div class='section'>
    
    <%= simple_form_for(
        :filter, url: filter_name_home_index_path, method: 'get',
        html: { class: 'form-inline' }, 
        wrapper: :inline_form,
        wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
      }) do |f| %>

      <%= f.input :name, placeholder: 'Digite o nome do contribuinte', input_html: {size: 80}, skip_label: true %>
      <%= f.input :cna, placeholder: 'Digite o número da CNA', input_html: {size: 40}, skip_label: true %> 
      <%= f.input :cpf, placeholder: 'Digite  número do CPF', input_html: {size: 40}, skip_label: true %> 
      <%= f.button :submit, 'Pesquisar', class: 'btn-primary' %>
    <% end %>

    <% unless @taxpayers.nil? %>
      <div class='list1'>
        <div class='subtitle_page'> <%= 'Contribuinte(s) Encontrado(s)' %> </div>

        <% @taxpayers.each do |taxpayer| %>
          <li>
            <div class='strip' id='none'> <%= taxpayer.id %> </div>

            <div class='indent'>
              <% unless Taxpayer.debtor? taxpayer %>
                <span class="btn btn-success btn-xs"> <%= "Sem débitos" %> </span>
                &bull;
              <% else %>

                <% unless Taxpayer.chargeble? taxpayer %>
                  <a class="btn btn-danger btn-xs"> <%= "Cidade não liberada para cobrança" %> </a>
                  &bull;
                <% end %>
              <% end %>

              <% if current_user.user? && current_user.id != taxpayer.user_id %>
                <%= taxpayer.name %>                
              <% else %>
                <%= link_to(taxpayer.name, show_path(taxpayer)) %>
              <% end %>

              &bull;
              <b><%= taxpayer.user.name if taxpayer.user_id %></b>
              &bull;

              <tt>
                <%= taxpayer.cpf %>
                &bull;
                <%= taxpayer.address %>
                &bull;
                <%= taxpayer.city.name if taxpayer.city %>
                &bull;
                <%= taxpayer.city.state if taxpayer.city %>
              </tt>
              <dt>
              </dt>
            </div>
          </li>
        <% end %>

        <% unless @taxpayers.empty? %>
          <div class="apple_pagination">
            <%= will_paginate @taxpayers, :container => false %>
          </div>
          <br>
        <% end %>

      </div>
    <% end %>
  </div>

  <% if current_user.admin? || current_user.user? %>
    <%= render "index_taxpayers_in_debt" %>
    <%= render "index_list_last_contracts" %>
    <br>
  <% end %>


  <div class="row">
    <div class="col-md-6">
      <%= render 'index_list_resumo' %>
    </div>
    <div class="col-md-3">
      <%= render 'index_count_contracts_deal_month_for_users' %>
    </div>
    <div class="col-md-3">
      <%= render 'index_count_contracts_deal_day_for_users' %>
    </div>  
  </div>


  <div class="row">
    <div class="col-md-12">
      <%= render 'index_list_last_histories' %>
    </div>
  </div>
  
<% end  %>


<% if @taxpayer %>

  <br>
  <div class='title'>
    <span> <%= 'Informações sobre Contribuinte - ' << @taxpayer.name %> </span>
  </div>

  <div class="row marketing">
    <div class="col-sm-6 col-md-3">
      <br>
      <div class="panel panel-primary">
        <%= render 'show_taxpayer' %> 
      </div>
    </div>

    <div class="col-sm-6 col-md-9">

      <div class='title_tools'>
        <% if @cnas_negotiables.count > 0 %> 
          <% if Taxpayer.chargeble?(@taxpayer) %>
            <a class="btn btn-large btn-warning" <%= link_to(t('home.deal'), deal_url(cod: @taxpayer.id)) %> </a>
          <% else %>
            <a class="btn btn-large btn-danger"> <%= "Cidade não liberada para cobrança" %> </a>
          <% end %>
        <% end %>
      </div>
      
      <%= render 'index_cnas_negotiables' if @cnas_negotiables.present? %>
      <%= render 'index_cnas_not_negotiables' if @cnas_not_negotiables.present? %>
      <%= render 'index_cnas_lawyers' if @cnas_lawyers.present? %>
      <%= render 'index_contracts_for_taxpayer' if @contracts_for_taxpayer.present? %>
      <%= render 'histories' %>
      
    </div>
  </div>
<% end %>