config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root 'home#index'

  resources :units
  resources :clients
  resources :taxpayers
  resources :categories
  resources :lawyers
  resources :contracts
  resources :proposals
  resources :proposal_tickets
  resources :cnas
  resources :cities
  resources :taxpayer_contacts
  resources :histories
  resources :remittances
  resources :bank_billets
  resources :discharges
  resources :users
  resources :words
  resources :tickets

  resources :user, :controller => 'users'

  resources :home do
    collection do
      get 'filter_name' => 'home#filter_name'
      get :get_tasks
      get :get_click
    end
  end

  get 'get_client' => 'clients#get_client'
  get 'set_client' => 'clients#set_client'

  get 'home/:cod/show' => 'home#show', as: :show
  get 'home/:cod/deal' => 'home#deal', as: :deal
  get 'home/:cod/get_cna' => 'home#get_cna', as: :get_cna
  patch 'home/:cod/pay_cna' => 'home#pay_cna', as: :pay_cna
  patch 'home/:cod/set_cna_to_normal' => 'home#set_cna_to_normal', as: :set_cna_to_normal
  patch 'home/:cod/set_cna' => 'home#set_cna', as: :set_cna
  get 'home/:cod/set_charge_cna' => 'home#set_charge_cna', as: :set_charge_cna
  get 'home/:cod/get_tickets' => 'home#get_tickets', as: :get_tickets
  get 'home/:cod/set_tickets' => 'home#set_tickets', as: :set_tickets
  get 'home/:cod/get_taxpayer' => 'home#get_taxpayer', as: :get_taxpayer
  patch 'home/:cod/set_taxpayer' => 'home#set_taxpayer', as: :set_taxpayer
  get 'home/:cod/set_lawyer_to_cna' => 'home#set_lawyer_to_cna', as: :set_lawyer_to_cna

  post 'proposal/:cod/create_proposal' => 'proposals#create_proposal', as: :create_proposal
  post 'proposal/:cod/cancel_proposal' => 'proposals#cancel_proposal', as: :cancel_proposal

  post 'contract/:cod/create_contract_from_proposal' => 'contracts#create_contract_from_proposal', as: :create_contract_from_proposal
  post 'contract/:cod/create_contract' => 'contracts#create_contract', as: :create_contract
  get 'contract/:contract/delete_contract' => 'contracts#delete_contract', as: :delete_contract
  get 'contract/:cod/contract_pdf' => 'contracts#contract_pdf', as: :contract_pdf
  get 'contract/:cod/contract_transaction_pdf' => 'contracts#contract_transaction_pdf', as: :contract_transaction_pdf
  get 'contract/:cod/create_bank_billet' => 'contracts#create_bank_billet', as: :create_bank_billet

  get 'ticket/:cod/create_new_expire_at' => 'tickets#create_new_expire_at', as: :create_new_expire_at
  get 'ticket/:cod/update_status_ticket' => 'tickets#update_status_ticket', as: :update_status_ticket
  
  post 'remittance/remittance_create' => 'remittances#remittance_create', as: :remittance_create
  get 'remittance/remittance_new' => 'remittances#remittance_new', as: :remittance_new
  get 'remittance/:cod/remittance_download' => 'remittances#remittance_download', as: :remittance_download
  get 'bank_billet/:cod/bank_billet_show' => 'bank_billets#bank_billet_show', as: :bank_billet_show
  get 'bank_billet/:cod/bank_billet_cancel' => 'bank_billets#bank_billet_cancel', as: :bank_billet_cancel
  get 'discharge/sent_discharge' => 'discharges#sent_discharge', as: :sent_discharge
  post 'discharge/create_discharge' => 'discharges#create_discharge', as: :create_discharge

  get 'contract/report_payment_filter' => 'contracts#report_payment_filter', as: :report_payment_filter
  get 'contract/report_payment_action' => 'contracts#report_payment_action', as: :report_payment_action
  get 'contract/report_payment_action_pdf' => 'contracts#report_payment_action_pdf', as: :report_payment_action_pdf

  get 'contract/report_fee_filter' => 'contracts#report_fee_filter', as: :report_fee_filter
  get 'contract/report_fee_action' => 'contracts#report_fee_action', as: :report_fee_action
  
  get 'history/report_count_contacts_filter' => 'histories#report_count_contacts_filter', as: :report_count_contacts_filter
  get 'history/report_count_contacts_action' => 'histories#report_count_contacts_action', as: :report_count_contacts_action

  get 'cna/report_cna_lawyer_filter' => 'cnas#report_cna_lawyer_filter', as: :report_cna_lawyer_filter
  get 'cna/report_cna_lawyer_rel' => 'cnas#report_cna_lawyer_rel', as: :report_cna_lawyer_rel

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :unit
  belongs_to :taxpayer
  belongs_to :user
  belongs_to :contract
  belongs_to :client
  
  has_many :tickets
  has_many :cnas
  
  validates_presence_of :unit_id, :taxpayer_id, :client_id

	enum status: [:active, :cancel, :contract]

  def self.list(unit, client)
    self.where("unit_id = ? and client_id = ?", unit, client)
  end
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  respond_to :html
  layout 'window'

  def index
    if current_user.admin? || current_user.client?
      @proposals = Proposal.where("unit_id = ? and client_id = ?", current_user.unit_id, session[:client_id]).order('id DESC').paginate(:page => params[:page], :per_page => 20)
    else
      @proposals = Proposal.where("unit_id = ? and client_id = ? AND user_id = ?", current_user.unit_id, session[:client_id], current_user.id).order('id DESC').paginate(:page => params[:page], :per_page => 20)
    end
    respond_with @proposals, :layout => 'application'
  end

  def show
    @proposal = Proposal.where('id = ? and unit_id = ? and client_id = ?', params[:id].to_i, current_user.unit_id, session[:client_id]).first
    @tickets = ProposalTicket.list(params[:id]).order('ticket_number')
    respond_with @proposal
  end

  def create_proposal
    cod = params[:cod]

    taxpayer = Taxpayer.find(cod)
    cnas = Cna.list(current_user.unit_id, session[:client_id]).not_pay.where('taxpayer_id = ? and fl_charge = ?', cod, true)
    unit = Unit.find(current_user.unit_id)

    ActiveRecord::Base.transaction do
      @proposal = Proposal.new

      @proposal.unit_id = current_user.unit_id
      @proposal.client_id = session[:client_id]
      @proposal.user_id = current_user.id
      @proposal.taxpayer_id = cod
      
      if session[:tickets].count == 2
        unit_amount = session[:total_fee_a_vista].to_f
        @proposal.unit_amount = unit_amount.round(2)

        client_amount = session[:total_cna_a_vista].to_f - session[:total_fee_a_vista].to_f
        @proposal.client_amount = client_amount.round(2)
        
        @proposal.client_ticket_quantity = 1

      else
        unit_amount = session[:total_fee_cobrado].to_f
        @proposal.unit_amount = unit_amount.round(2)

        client_amount = session[:total_cna_cobrado].to_f - session[:total_fee_cobrado].to_f
        @proposal.client_amount = client_amount.round(2)
        
        @proposal.client_ticket_quantity = session[:tickets].count - 1
      end
      
      @proposal.unit_ticket_quantity = 1
      @proposal.unit_fee = 10
      @proposal.status = 0

      @proposal.save!

      n = 0
      session[:tickets].each  do |tic|
        n = n + 1
        @ticket = ProposalTicket.new
        @ticket.unit_id = session[:unit_id]
        @ticket.proposal_id = @proposal.id
        @ticket.ticket_type = 0 if tic['unit_amount'].to_f == 0
        @ticket.ticket_type = 1 if tic['unit_amount'].to_f > 0
        
        @ticket.amount = tic['client_amount'].to_f if tic['client_amount'].to_f > 0
        @ticket.amount = tic['unit_amount'].to_f if tic['unit_amount'].to_f > 0
        
        @ticket.due_at = tic['due'].to_date
        @ticket.ticket_number = n

        @ticket.save!
      end

      cnas.each do  |cna|
        cna.proposal_id = @proposal.id
        cna.proposal!
        cna.save!
      end
    end
    respond_with @proposal, notice: 'Proposta criada com sucesso.'
  end


  def cancel_proposal
    cod = params[:cod]
    proposal = Proposal.find(cod)

    if proposal.contract?
      flash[:alert] = "Ação não permitida. Proposta ja gerou um TERMO NRO " << proposal.contract_id.to_s
      redirect_to :proposals and return
    end 

    if proposal.cancel?
      flash[:alert] = "Ação não permitida. Proposta ja esta cancelada"
      redirect_to :proposals and return
    end 

    cnas = Cna.list(current_user.unit_id, session[:client_id]).where('proposal_id = ?', cod)

    ActiveRecord::Base.transaction do
      cnas.each do  |cna|
        cna.proposal_id = nil
        cna.status = :not_pay
        cna.save!
      end

      proposal.status = :cancel
      proposal.save!
    end
    respond_with proposal, alert: 'Proposta CANCELADA com sucesso.'
  end

  private
  def proposal_params
    params.require(:proposal).permit(:unit_id, :client_id, :user_id, :unit_ticket_quantity, :client_ticket_quantity )
  end

end

app/views/proposals/index.html.erb
<div class='title_page'>
  <span> <%= t('proposal.title') %> </span>
</div>

<p id="notice"><%= notice %></p>

<div class='list1'>
  <% unless @proposals.empty? %>
    <% @proposals.each do |proposal| %>
      <li>
        <div class='strip' id='none'> <%= proposal.id %> </div>

        <div class='indent'>
          <% if proposal.contract? %>
            <span class="label label-success"><%= t('proposal.status.'<< proposal.status, :contract => proposal.contract_id ) %> </span> 
          <% elsif proposal.cancel? %>
            <span class="label label-danger"><%= t('proposal.status.'<< proposal.status ) %> </span> 
          <% else %>
            <span class="label label-primary"><%= t('proposal.status.'<< proposal.status ) %> </span> 
          <% end %>
          &nbsp;
          <%= proposal.taxpayer.origin_code %>
          &bull;
          <%= link_to(proposal.taxpayer.name, proposal_path(proposal)) %>
          &bull;
          <%= 'Termo gerado: ' << proposal.contract_id.to_s if proposal.contract? %>
          <dt></dt>
        </div>
      </li>
    <% end %>
  <% else %>
    Colaborador não tem propostas geradas.
  <% end %>
</div>

<div id='paginate'>
  <div class="apple_pagination">
    <%= will_paginate @proposals, :container => false  if @proposals.present? %>
  </div>
</div>

app/views/proposals/show.html.erb
<div class='title_tools'>
  <%= link_to(t('proposal.index'), proposals_path, class: "btn btn-large btn-warning") %>
  
  <% if @proposal.active? %>
    <%= link_to(t('proposal.create_contract'), create_contract_from_proposal_path(@proposal.id), method: 'post', class: "btn btn-large btn-success") %>
  <% end %>

  <% if @proposal.active? %>
    <%= link_to(t('proposal.delete_proposal'), cancel_proposal_path(@proposal.id), method: 'post', class: "btn btn-large btn-danger", data: {confirm: 'Você tem certeza de que deseja CANCELAR a proposta gerada?'}) %>
  <% end %>
</div>

<div class='title_page'> <%= t('proposal.show') %> </div>

<div class='section'>
  <div class='label1 top req'> <%=t("id") %>: </div>
  <%= @proposal.id %>
  
  <div class='label1 top req'> <%=t("status") %>: </div>
  <% if @proposal.contract? & @proposal.contract_id %>
    <span class="label label-success"><%= link_to( t('proposal.status.'<< @proposal.status, :contract => @proposal.contract_id), contract_path(@proposal.contract_id)) %> </span> 
  <% elsif @proposal.cancel? %>
    <span class="label label-danger"><%= t('proposal.status.'<< @proposal.status) %> </span> 
  <% else %>
    <span class="label label-primary"><%= t('proposal.status.'<< @proposal.status) %> </span> 
  <% end %>
  
  <div class='label1 top req'> <%=t("proposal.contract_date") %>: </div>
  <%= @proposal.created_at.to_s_br %>

  <div class='label1 top req'> <%=t("proposal.taxpayer") %>: </div>
  <%= link_to(@proposal.taxpayer.origin_code.to_s << " - " << @proposal.taxpayer.name, show_path(@proposal.taxpayer_id)) %>
  
  <div class='label1 top req'> <%=t("user.name") %>: </div>
  <%= @proposal.user ? @proposal.user.name : 'ADMIN'  %>
	
  <div class='label1 top req'> <%=t("proposal.amount", name: @proposal.unit.name) %>: </div>
  <%= @proposal.unit_amount.real %>
	
  <div class='label1 top req'> <%=t("proposal.unit_fee", name: @proposal.unit.name) %>: </div>
  <%= @proposal.unit_fee.real %>
	
  <div class='label1 top req'> <%=t("proposal.ticket_quantity", name: @proposal.unit.name) %>: </div>
  <%= @proposal.unit_ticket_quantity %>
	
  <div class='label1 top req'> <%=t("proposal.amount", name: @proposal.taxpayer.client.name) %>: </div>
  <%= @proposal.client_amount.real %>
	
  <div class='label1 top req'> <%=t("proposal.ticket_quantity", name: @proposal.taxpayer.client.name) %>: </div>
  <%= @proposal.client_ticket_quantity %>
</div>


<div class='subtitle'> <%= 'Parcelas' %> </div>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Vencimento</th>
      <th>Valor de Parcela GMA</th>
      <th>Valor de Parcela Cliente</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% unless @tickets.nil? %>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.ticket_number %> </td>
          <td><%= ticket.due_at.to_date.to_s_br %> </td>
          <td><%= ticket.amount.real if ticket.unit? %> </td>
          <td><%= ticket.amount.real if ticket.client? %> </td>
          <td>
            <% unless @proposal.contract? %>
              <div class='tools'>
                <%= link_to(t('menu.edit'), edit_proposal_ticket_path(ticket), class: "btn btn-xs btn-default") %>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>