config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root 'home#index'

  resources :units
  resources :clients
  resources :taxpayers
  resources :categories
  resources :lawyers
  resources :contracts
  resources :proposals
  resources :proposal_tickets
  resources :cnas
  resources :cities
  resources :taxpayer_contacts
  resources :histories
  resources :remittances
  resources :bank_billets
  resources :discharges
  resources :users
  resources :words
  resources :tickets

  resources :user, :controller => 'users'

  resources :home do
    collection do
      get 'filter_name' => 'home#filter_name'
      get :get_tasks
      get :get_click
    end
  end

  get 'get_client' => 'clients#get_client'
  get 'set_client' => 'clients#set_client'

  get 'home/:cod/show' => 'home#show', as: :show
  get 'home/:cod/deal' => 'home#deal', as: :deal
  get 'home/:cod/get_cna' => 'home#get_cna', as: :get_cna
  patch 'home/:cod/pay_cna' => 'home#pay_cna', as: :pay_cna
  patch 'home/:cod/set_cna_to_normal' => 'home#set_cna_to_normal', as: :set_cna_to_normal
  patch 'home/:cod/set_cna' => 'home#set_cna', as: :set_cna
  get 'home/:cod/set_charge_cna' => 'home#set_charge_cna', as: :set_charge_cna
  get 'home/:cod/get_tickets' => 'home#get_tickets', as: :get_tickets
  get 'home/:cod/set_tickets' => 'home#set_tickets', as: :set_tickets
  get 'home/:cod/get_taxpayer' => 'home#get_taxpayer', as: :get_taxpayer
  patch 'home/:cod/set_taxpayer' => 'home#set_taxpayer', as: :set_taxpayer
  get 'home/:cod/set_lawyer_to_cna' => 'home#set_lawyer_to_cna', as: :set_lawyer_to_cna

  post 'proposal/:cod/create_proposal' => 'proposals#create_proposal', as: :create_proposal
  post 'proposal/:cod/cancel_proposal' => 'proposals#cancel_proposal', as: :cancel_proposal

  post 'contract/:cod/create_contract_from_proposal' => 'contracts#create_contract_from_proposal', as: :create_contract_from_proposal
  post 'contract/:cod/create_contract' => 'contracts#create_contract', as: :create_contract
  get 'contract/:contract/delete_contract' => 'contracts#delete_contract', as: :delete_contract
  get 'contract/:cod/contract_pdf' => 'contracts#contract_pdf', as: :contract_pdf
  get 'contract/:cod/contract_transaction_pdf' => 'contracts#contract_transaction_pdf', as: :contract_transaction_pdf
  get 'contract/:cod/create_bank_billet' => 'contracts#create_bank_billet', as: :create_bank_billet

  get 'ticket/:cod/create_new_expire_at' => 'tickets#create_new_expire_at', as: :create_new_expire_at
  get 'ticket/:cod/update_status_ticket' => 'tickets#update_status_ticket', as: :update_status_ticket
  
  post 'remittance/remittance_create' => 'remittances#remittance_create', as: :remittance_create
  get 'remittance/remittance_new' => 'remittances#remittance_new', as: :remittance_new
  get 'remittance/:cod/remittance_download' => 'remittances#remittance_download', as: :remittance_download
  get 'bank_billet/:cod/bank_billet_show' => 'bank_billets#bank_billet_show', as: :bank_billet_show
  get 'bank_billet/:cod/bank_billet_cancel' => 'bank_billets#bank_billet_cancel', as: :bank_billet_cancel
  get 'discharge/sent_discharge' => 'discharges#sent_discharge', as: :sent_discharge
  post 'discharge/create_discharge' => 'discharges#create_discharge', as: :create_discharge

  get 'contract/report_payment_filter' => 'contracts#report_payment_filter', as: :report_payment_filter
  get 'contract/report_payment_action' => 'contracts#report_payment_action', as: :report_payment_action
  get 'contract/report_payment_action_pdf' => 'contracts#report_payment_action_pdf', as: :report_payment_action_pdf

  get 'contract/report_fee_filter' => 'contracts#report_fee_filter', as: :report_fee_filter
  get 'contract/report_fee_action' => 'contracts#report_fee_action', as: :report_fee_action
  
  get 'history/report_count_contacts_filter' => 'histories#report_count_contacts_filter', as: :report_count_contacts_filter
  get 'history/report_count_contacts_action' => 'histories#report_count_contacts_action', as: :report_count_contacts_action

  get 'cna/report_cna_lawyer_filter' => 'cnas#report_cna_lawyer_filter', as: :report_cna_lawyer_filter
  get 'cna/report_cna_lawyer_rel' => 'cnas#report_cna_lawyer_rel', as: :report_cna_lawyer_rel

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :unit
   
  has_many :tasks
  
  validates_presence_of :name, :unit_id

  def self.list(unit)
    self.where("unit_id = ?", unit).order("name ASC")
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  respond_to :html
  layout 'window'

  def index
    @categories = index_class(Category)
    respond_with @categories, :layout => 'application'
  end

  def show
    @category = Category.find(params[:id])
    respond_with @action
  end

  def new
    @category = Category.new
    respond_with @category
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.unit_id = session[:unit_id]
    @category.save!
    respond_with @category
    
  rescue ActiveRecord::RecordInvalid => exception
    respond_with @category
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(category_params)
    respond_with @category
  end

  private
    def category_params
      params.require(:category).permit(:name, :unit_id)
    end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
	<div class='section'>
    <%= f.input :name, :label => t('category.name'), input_html:{:class => 'form-control'} %>

  	<div class="actions">
  		<div class='buttonbar'>
        <%= f.button :submit, t('menu.save'), class: 'btn-primary' %>
        <%= 'ou' %>
        <%= link_to t('menu.cancel'), categories_path %>
  		</div>
    </div>

  </div>

<% end %>

app/views/categories/edit.html.erb
<div class='title'> <%= t('category.edit') %> </div>

<%= render "form"%>

app/views/categories/index.html.erb
<div class='title_tools'>
	<a class="btn btn-large btn-warning" <%= link_to(t('category.new'), new_category_path) %> </a>
</div>

<div class='title_page'>
	<span> <%= t('category.title') %> </span>
</div>

<div class='list1'>
	<% unless @categories.empty? %>
		<% @categories.each do |category| %>
			<li>
				<div class='strip' id='none'> <%= category.id %> </div>

				<div class='tools'>
					<%= link_to(t('menu.edit'), edit_category_path(category), class: "btn btn-xs btn-default") %>
				</div>

				<div class='indent'>
					<%= link_to(category.name, category_path(category)) %>
					<tt>
					</tt>
					<dt>
					</dt>
				</div>
			</li>
		<% end %>
	<% end %>
</div>

<div id='paginate'><%= render 'common/paginate' %></div>

app/views/categories/new.html.erb
<div class='title'> <%= t('category.new') %> </div>

<%= render "form"%>

app/views/categories/show.html.erb
<div class='title_tools'>
	<a class="btn btn-large btn-warning" <%= link_to(t('category.new'), new_category_path) %> </a>
	<a class="btn btn-large btn-warning" <%= link_to(t('category.index'), categories_path) %> </a>
</div>

<div class='title_page'> <%= t('category.show') %> </div>

<div class='section'>
	<div class='label1 top req'> <%=t("category.name") %>: </div>			<%= @category.name %>
</div>